Repository knit-pk/homepage-nuxtjs, pull requests merged in 2018-03, with the labels that each got.

#80 Bugfix/article resources
  components/article/ArticleBreadcrumb.vue
  components/article/ArticleCard.vue
  components/article/ArticleCardList.vue
  components/article/ArticleFooter.vue
  components/article/ArticleSingle.vue
  pages/articles/_slug.vue
  store/articles/item.js
  store/articles/list.js
  store/articles/settings.js
  yarn.lock
Labels: bug

#81 Update package constraints
  package.json
  yarn.lock
Labels: feature

#82 Optimize FixedTop scrolling
  components/mixins/FixedTop.js
  package.json
  yarn.lock
Labels: wip

#87 Add styles for links in article
  assets/scss/variables/components/article/_article-content.scss
  components/article/ArticleContent.vue
Labels: ready for review

#77 Feature/docker integration
  .dockerignore
  .env.example
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  config/logger/index.js
  deploy/docker-app-push.sh
  docker-compose.yml
  helpers/commonHelper.js
  jsconfig.json
  nuxt.config.js
  package.json
  yarn.lock
Labels: feature, ready for review

#89 Configure heroku deployment
  components/commons/KnitFooter.vue
  deploy/docker-app-push.sh
  package.json
Labels: feature, ready for review

#90 Improve the styling of links
  assets/scss/main.scss
  assets/scss/mixins/_mixins.scss
  assets/scss/variables/components/article/_article-content.scss
  assets/scss/variables/components/widgets/_job-offers-widget.scss
  assets/scss/variables/components/widgets/partials/_job-offers-widget-item.scss
  assets/scss/variables/components/widgets/partials/_projects-widget-item.scss
  components/article/ArticleCard.vue
  components/article/ArticleContent.vue
  components/widgets/partials/JobOffersWidgetItem.vue
  components/widgets/partials/ProjectsWidgetItem.vue
Labels: feature, ready for review

#88 Rationale for switching to yarn
  .travis.yml
  README.md
  docs/components.org
  docs/package-manager.org
Labels: feature, ready for review

#86 Add RWD for article footer
  components/article/ArticleFooter.vue
Labels: feature

#78 Add wrapper to show/hide components with config
  components/article/ArticleBreadcrumb.vue
  components/article/ArticleCard.vue
  components/article/ArticleCardList.vue
  components/article/ArticleComment.vue
  components/article/ArticleComments.vue
  components/article/ArticleContent.vue
  components/article/ArticleFooter.vue
  components/article/ArticleList.vue
  components/article/ArticleSingle.vue
  components/commons/KnitButton.vue
  components/commons/KnitFooter.vue
  components/commons/KnitHeader.vue
  components/commons/KnitLogo.vue
  components/commons/KnitMenuMobile.vue
  components/commons/KnitNavbar.vue
  components/commons/Searchbar.vue
  components/commons/SiteHeading.vue
  components/widgets/ActionLinksWidget.vue
  components/widgets/AlertWidget.vue
  components/widgets/JobOffersWidget.vue
  components/widgets/MeetupCalendarWidget.vue
  components/widgets/PopularArticlesWidget.vue
  components/widgets/ProjectsWidget.vue
  components/widgets/RecommendedArticlesWidget.vue
  config/components-config.json
  directives/client/config.js
  directives/client/index.js
  directives/ssr/config.js
  directives/ssr/index.js
  nuxt.config.js
  package-lock.json
  package.json
  plugins/inject-directives.js
  plugins/vue-config-manager.js
  yarn.lock
Labels: feature, ready for review

#79 Fix latex rendering
  .gitignore
  assets/scss/_imports.scss
  assets/scss/custom-components/katex-integration.scss
  assets/scss/main.scss
  assets/scss/variables/components/article/_article-content.scss
  components/article/ArticleBreadcrumb.vue
  components/article/ArticleContent.vue
  components/article/ArticleFooter.vue
  nuxt.config.js
  package-lock.json
  pages/articles/_slug.vue
  static/fonts/flaticon/flaticon.html
Labels: feature, ready for review

#96 Configure auto-tagging on master
  .travis.yml
  Dockerfile
  deploy/docker-app-push.sh
  deploy/github-tag.sh
  package.json
Labels: wip

#97 Fix docs rendering on gh
  docs/components-conventions.org
  docs/package-manager.org
Labels: bug, ready for review

#92 Add microdata to article and article-card
  components/article/ArticleCard.vue
  components/article/ArticleCardList.vue
  components/article/ArticleContent.vue
  components/article/ArticleFooter.vue
  components/article/ArticlePublisherMeta.vue
  components/article/ArticleSingle.vue
  pages/articles/_slug.vue
  store/articles/settings.js
Labels: feature, ready for review

#98 Hide unused components
  components/article/ArticleComment.vue
  components/article/ArticleComments.vue
  components/widgets/ActionLinksWidget.vue
  config/components-config.json
Labels: ready for review

#100 Feature/use stage api url
  deploy/docker-app-push.sh
  package.json
Labels: feature, ready for review

#104 Update deps and lock
  docker-compose.yml
  package.json
  yarn.lock
Labels: bug
